@startuml
:Cliente:
usecase (Meter dinero)
usecase (Pedir azucar)
usecase (Pedir Procucto)
usecase (Cancelar)
usecase (Devolver dinero)
:Cliente: -- (Meter dinero)
:Cliente: -- (Pedir azucar)
:Cliente: -- (Pedir Procucto)
:Cliente: -- (Cancelar)
(Pedir Procucto) ..>"<<include>>" (Devolver dinero)
(Cancelar) ..>"<<include>>" (Devolver dinero)
@enduml