@startuml
:new Actor:
usecase (Identificarse)
usecase (Pagar)
usecase (Eligir mensajero)
usecase (Confirmar)
usecase (Registrarse)
usecase (Pagar con tarjeta)
usecase (Pagar con transferencia)
@enduml